Here are a few relevant projects related to machine learning in option trading that you can find on GitLab:

Option Pricing and Greeks with Python:
This project provides an implementation of the Black-Scholes model for option pricing in Python. It also includes code for calculating option Greeks, such as delta, gamma, and theta. The code is well-documented and can be easily adapted for different use cases.
Link: https://gitlab.com/snippets/2043283

Reinforcement Learning for Option Trading:
This project uses reinforcement learning to develop a trading strategy for options. The agent learns to make decisions about buying and selling options based on historical data and feedback from the market. The code includes a detailed explanation of the reinforcement learning algorithm and can be used as a starting point for building your own trading strategy.
Link: https://gitlab.com/pravin1220/reinforcement-learning-for-option-trading

Predicting Option Prices with Neural Networks:
This project uses a neural network to predict the prices of options based on historical market data. The code includes a Jupyter notebook with step-by-step instructions for building and training the neural network. The notebook also includes code for visualizing the predictions and evaluating the model's accuracy.
Link: https://gitlab.com/nadimbioinfo/predicting-option-prices-with-neural-networks

Portfolio Optimization with Genetic Algorithms:
This project uses a genetic algorithm to optimize a portfolio of options based on historical market data. The code includes an implementation of the genetic algorithm in Python, as well as a Jupyter notebook with examples of how to use the algorithm to optimize portfolios based on different criteria.
Link: https://gitlab.com/panpanmade/portfolio-optimization-with-genetic-algorithms

These are just a few examples of relevant projects related to machine learning in option trading that you can find on GitLab. There are many other projects available, depending on your interests and expertise.

In [2]:
import sys

sys.path.append(r'\Users\jimhu\option_trader\src')

from option_trader.utils.data_getter import get_price_history

watchlist = ['MSFT', 'AAPL', 'AMZN', 'NVDA', 'BLDR', 'GOOGL', 'NFLX', 'META', 'SPY', 'QQQ', 'AMD', 'TSLA', 'ISRG']

In [55]:
df = get_price_history('AAPL', period='1y')

#hist['Date'] = hist.index

df = df.rename_axis(['Date']).reset_index()

In [61]:
df = get_price_history('MSFT', period='1y')

#hist['Date'] = hist.index

df = df.rename_axis(['Date']).reset_index()

import datetime

df.loc[0]['Date'].weekday()

df['weekday'] = df['Date'].apply(lambda x: x.weekday())

df = df[df['weekday']==4]

df['Close Diff'] = df['Close'].diff(periods=1)

df['Close Diff'] = df['Close Diff']/df['Close']

df['Date Diff'] = df['Date'].diff(periods=1)


df

#import matplotlib.pyplot as plt

#df.plot(x='Date', y=['Close Diff'], kind='line')
#plt.show()

#friday_df = df[df['weekday']==4]

#friday_df['Cllose Diff'] = friday_df['Close'].diff()

#friday_df['Date Diff'] = friday_df['Date'].diff()

#friday_df
#df['5 days change'][i] = df['Close'][i] - df['Close'][i-5]

#df.at[i, '5 days change %'] = round((((last_price-price_history['Close'][-6])/last_price)*100),2)

#datetime.datetime(2012, 3, 23, 23, 24, 55, 173504)
#datetime.datetime.today().weekday()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,weekday,Close Diff,Date Diff
4,2022-08-19 00:00:00-04:00,286.741508,287.088899,283.426466,284.012054,20570000,0.0,0.0,4,NaN,NaT
9,2022-08-26 00:00:00-04:00,276.994886,278.245482,265.977842,266.087006,27549300,0.0,0.0,4,-0.067365,7 days 00:00:00
14,2022-09-02 00:00:00-04:00,259.744742,262.762007,252.568749,254.146866,22855400,0.0,0.0,4,-0.046981,7 days 00:00:00
18,2022-09-09 00:00:00-04:00,258.553696,263.248367,258.345273,262.484100,22084700,0.0,0.0,4,0.031763,7 days 00:00:00
23,2022-09-16 00:00:00-04:00,242.435029,243.467267,240.251469,242.911453,39791800,0.0,0.0,4,-0.080575,7 days 00:00:00
28,2022-09-23 00:00:00-04:00,237.750302,239.328434,233.442731,236.142410,34176000,0.0,0.0,4,-0.028665,7 days 00:00:00
33,2022-09-30 00:00:00-04:00,236.509625,238.742814,230.991169,231.159897,35694800,0.0,0.0,4,-0.021554,7 days 00:00:00
38,2022-10-07 00:00:00-04:00,239.100143,239.517019,231.427901,232.489914,37769600,0.0,0.0,4,0.005721,7 days 00:00:00
43,2022-10-14 00:00:00-04:00,233.780186,235.467497,226.633983,226.852341,30198600,0.0,0.0,4,-0.024851,7 days 00:00:00
48,2022-10-21 00:00:00-04:00,232.986169,241.184450,232.747957,240.311020,26299700,0.0,0.0,4,0.056005,7 days 00:00:00
53,2022-10-28 00:00:00-04:00,224.549686,234.832284,224.361104,234.107727,40647700,0.0,0.0,4,-0.026498,7 days 00:00:00
58,2022-11-04 00:00:00-04:00,215.924610,219.934419,211.835381,219.735916,36789100,0.0,0.0,4,-0.065405,7 days 00:00:00
63,2022-11-11 00:00:00-05:00,241.174535,246.137178,240.122442,245.263748,34620200,0.0,0.0,4,0.104083,7 days 01:00:00
68,2022-11-18 00:00:00-05:00,242.371757,242.600693,237.912703,240.092468,27613500,0.0,0.0,4,-0.021539,7 days 00:00:00
72,2022-11-25 00:00:00-05:00,246.154009,247.537511,245.576718,246.333176,9200800,0.0,0.0,4,0.025334,7 days 00:00:00
77,2022-12-02 00:00:00-05:00,248.652282,254.863104,248.522884,253.827972,21528500,0.0,0.0,4,0.029527,7 days 00:00:00
82,2022-12-09 00:00:00-05:00,243.556191,247.149318,243.018722,244.272827,20609700,0.0,0.0,4,-0.039117,7 days 00:00:00
87,2022-12-16 00:00:00-05:00,247.388207,248.672171,242.371757,243.546249,86102000,0.0,0.0,4,-0.002983,7 days 00:00:00
92,2022-12-23 00:00:00-05:00,235.006357,237.753450,232.846502,237.614105,21207000,0.0,0.0,4,-0.024965,7 days 00:00:00
96,2022-12-30 00:00:00-05:00,237.096545,238.838365,235.553787,238.699020,21938500,0.0,0.0,4,0.004545,7 days 00:00:00
100,2023-01-06 00:00:00-05:00,221.957645,224.704739,218.324712,223.878616,43613600,0.0,0.0,4,-0.066198,7 days 00:00:00
105,2023-01-13 00:00:00-05:00,235.892183,238.251100,233.821904,238.111755,21333300,0.0,0.0,4,0.059775,7 days 00:00:00
109,2023-01-20 00:00:00-05:00,233.762206,239.614726,233.413836,239.097153,35389800,0.0,0.0,4,0.004121,7 days 00:00:00
114,2023-01-27 00:00:00-05:00,247.826153,248.662223,245.676246,247.000031,26498900,0.0,0.0,4,0.031995,7 days 00:00:00
119,2023-02-03 00:00:00-05:00,258.326835,262.965056,255.898238,257.142395,29077300,0.0,0.0,4,0.039443,7 days 00:00:00
124,2023-02-10 00:00:00-05:00,260.307540,262.855572,259.441612,261.870209,25818500,0.0,0.0,4,0.018054,7 days 00:00:00
129,2023-02-17 00:00:00-05:00,258.824217,259.522672,255.441597,257.497101,30000100,0.0,0.0,4,-0.016983,7 days 00:00:00
133,2023-02-24 00:00:00-05:00,249.414768,250.452492,247.558824,248.676376,24990900,0.0,0.0,4,-0.035471,7 days 00:00:00
138,2023-03-03 00:00:00-05:00,251.639895,255.062406,250.841637,254.733124,30760100,0.0,0.0,4,0.023777,7 days 00:00:00
143,2023-03-10 00:00:00-05:00,250.532319,252.238580,247.059914,248.047745,28333900,0.0,0.0,4,-0.026952,7 days 00:00:00
148,2023-03-17 00:00:00-04:00,277.653034,282.711952,275.717264,278.820465,69527400,0.0,0.0,4,0.110368,6 days 23:00:00
153,2023-03-24 00:00:00-04:00,276.635254,280.017875,274.679538,279.958008,28172000,0.0,0.0,4,0.004063,7 days 00:00:00
158,2023-03-31 00:00:00-04:00,283.111104,288.638997,282.382685,287.671112,32766000,0.0,0.0,4,0.026812,7 days 00:00:00
167,2023-04-14 00:00:00-04:00,286.373979,287.850761,283.071201,285.515869,20987900,0.0,0.0,4,-0.007549,14 days 00:00:00
172,2023-04-21 00:00:00-04:00,284.388324,285.645555,282.442565,285.136688,21676400,0.0,0.0,4,-0.001330,7 days 00:00:00
177,2023-04-28 00:00:00-04:00,303.346872,308.256123,302.648387,306.589783,36446700,0.0,0.0,4,0.069973,7 days 00:00:00
182,2023-05-05 00:00:00-04:00,305.053143,311.289510,303.606293,309.972382,28181200,0.0,0.0,4,0.010913,7 days 00:00:00
187,2023-05-12 00:00:00-04:00,309.872591,309.972379,305.931226,308.296051,19758100,0.0,0.0,4,-0.005437,7 days 00:00:00
192,2023-05-19 00:00:00-04:00,316.739990,318.750000,316.369995,318.339996,27529500,0.0,0.0,4,0.031551,7 days 00:00:00
197,2023-05-26 00:00:00-04:00,324.019989,333.399994,323.880005,332.890015,36630600,0.0,0.0,4,0.043708,7 days 00:00:00
201,2023-06-02 00:00:00-04:00,334.250000,337.500000,332.549988,335.399994,25864000,0.0,0.0,4,0.007484,7 days 00:00:00
206,2023-06-09 00:00:00-04:00,324.989990,329.989990,324.410004,326.790009,22514900,0.0,0.0,4,-0.026347,7 days 00:00:00
211,2023-06-16 00:00:00-04:00,351.320007,351.470001,341.950012,342.329987,46533600,0.0,0.0,4,0.045395,7 days 00:00:00
215,2023-06-23 00:00:00-04:00,334.359985,337.959991,333.450012,335.019989,23084700,0.0,0.0,4,-0.021820,7 days 00:00:00
220,2023-06-30 00:00:00-04:00,337.750000,342.730011,337.200012,340.540009,26823800,0.0,0.0,4,0.016210,7 days 00:00:00
224,2023-07-07 00:00:00-04:00,339.320007,341.790009,337.000000,337.220001,21185300,0.0,0.0,4,-0.009845,7 days 00:00:00
229,2023-07-14 00:00:00-04:00,347.589996,351.429993,344.309998,345.239990,28302200,0.0,0.0,4,0.023230,7 days 00:00:00
234,2023-07-21 00:00:00-04:00,349.149994,350.299988,339.829987,343.769989,69368900,0.0,0.0,4,-0.004276,7 days 00:00:00
239,2023-07-28 00:00:00-04:00,333.670013,340.010010,333.170013,338.369995,28484900,0.0,0.0,4,-0.015959,7 days 00:00:00
244,2023-08-04 00:00:00-04:00,331.880005,335.140015,327.239990,327.779999,23727700,0.0,0.0,4,-0.032308,7 days 00:00:00
249,2023-08-11 00:00:00-04:00,320.260010,322.410004,319.209991,321.010010,24342600,0.0,0.0,4,-0.021090,7 days 00:00:00

In [1]:
import sys

sys.path.append(r'\Users\jimhu\option_trader\src')
    
from tradingBot.excel import accountBook as act_wb
from tradingBot.excel import watchListBook as watch_wb
from tradingBot.settings import tradeConfig as cf
from tradingBot.consts import strategy as Strategy
from tradingBot.settings.tradeConfig import entryCrit, riskManager, marketCondition, runtimeConfig
from tradingBot.excel import accountBook as act_wb

import logging
import logging.config

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(levelname)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'level': 'INFO',
            'handlers': ['console'],
        },
    },
}

logging.config.dictConfig(LOGGING)

import warnings

warnings.filterwarnings("ignore")

In [2]:
risk_mgr = riskManager()

risk_mgr.stop_loss_percent = 50
risk_mgr.stop_gain_percent = 100
risk_mgr.close_days_before_earning = 1
risk_mgr.close_days_before_expire = 1
risk_mgr.open_min_days_to_earning = 4
risk_mgr.open_min_days_to_expire = 4
risk_mgr.max_option_positions = 10
risk_mgr.max_loss_per_position = 1500
                       
entry_crit = entryCrit()

entry_crit.max_rating = 1.8

runtime_config = runtimeConfig()
runtime_config.init_balance = 100000

market_condition = marketCondition()

In [3]:
#logging.basicConfig(level=logging.DEBUG)

data_dir = r'C:\Users\jimhu\option_trader\data\charts'

wb_file_path = r'C:\Users\jimhu\option_trader\data\users\jihuang\jihuang_watchlist.xlsm' 

ac_book_file_path = r'C:\Users\jimhu\option_trader\data\users\jihuang\jihuang_spread.xlsm' 

#watchBook = watch_wb.watchListBook(wb_file_path)

#watch_list = watchBook.get_all_watch_list()

acc_book = act_wb.accountBook(ac_book_file_path)

In [ ]:
#SPREAD
spread_acc_file_path = r'C:\Users\jimhu\option_trader\data\excell\jihuang-spread.xlsm'
spread_strategy_list = [Strategy.CREDIT_PUT_SPREAD, Strategy.DEBIT_PUT_SPREAD, Strategy.CREDIT_CALL_SPREAD, Strategy.DEBIT_PUT_SPREAD]

#IRON CONDOR
condor_acc_file_path = r'C:\Users\jimhu\option_trader\data\excell\jihuang-condor.xlsm'
condor_strategy_list = [Strategy.CREDIT_IRON_CONDOR, Strategy.DEBIT_IRON_CONDOR]

#Butterfly
butterfly_acc_file_path = r'C:\Users\jimhu\option_trader\data\excell\jihuang-butterfly.xlsm'
butterfly_strategy_list = [Strategy.CREDIT_CALL_BUTTERFLY, Strategy.CREDIT_PUT_BUTTERFLY, Strategy.DEBIT_CALL_BUTTERFLY, Strategy.DEBIT_PUT_BUTTERFLY, Strategy.IRON_BUTTERFLY, Strategy.REVERSE_IRON_BUTTERFLY]

In [ ]:
spread_accountBook = act_wb.accountBook(file_path=spread_acc_file_path,
                                 risk_mgr=risk_mgr, 
                                 entry_crit = entry_crit,
                                 runtime_config = runtime_config,
                                 market_condition = market_condition,
                                 strategy_list=spread_strategy_list)

condor_accountBook = act_wb.accountBook(file_path=condor_acc_file_path,
                                 risk_mgr=risk_mgr, 
                                 entry_crit = entry_crit,
                                 runtime_config = runtime_config,
                                 market_condition = market_condition,
                                 strategy_list=condor_strategy_list)

butterfly_accountBook = act_wb.accountBook(file_path=butterfly_acc_file_path,
                                 risk_mgr=risk_mgr, 
                                 entry_crit = entry_crit,
                                 runtime_config = runtime_config,
                                 market_condition = market_condition,
                                 strategy_list=butterfly_strategy_list)

In [ ]:
condor_accountBook.update_all_strategy_positions()
#butterfly_accountBook.update_all_strategy_positions()
#spread_accountBook.update_all_strategy_positions()

In [ ]:
spread_accountBook.try_stop_strategy_positions()
condor_accountBook.try_stop_strategy_positions()
butterfly_accountBook.try_stop_strategy_positions()

In [ ]:
from tradingBot.optionPosition import iron_condor as ic

q = ic.iron_condor_position('AAPL', entry_crit, runtime_config)
dfi = q.get_positions(condor_strategy_list)

In [ ]:
from tradingBot.excel import watchListBook as wb

watchBook = wb.watchListBook(wb_file_path, data_dir)

#watchBook.refresh_one_watch_list('Software', update_TD=True)
#watchBook.refresh_one_watch_list('Semi', update_TD=True)
#watchBook.refresh_one_watch_list('Foods', update_TD=True)
#watchBook.refresh_one_watch_list('Medical', update_TD=True)
#watchBook.refresh_one_watch_list('Travel', update_TD=True)
#watchBook.refresh_one_watch_list('Financial', update_TD=True)
#watchBook.refresh_one_watch_list('Retail', update_TD=True)
#watchBook.refresh_one_watch_list('Energy', update_TD=True)
#watchBook.refresh_one_watch_list('Manufacture', update_TD=True)
#watchBook.refresh_one_watch_list('ETF', update_TD=True)

watchBook.refresh_all_watch_list(update_TD=True)

In [ ]:
###############################################
# get option positions for all watch list     #
###############################################

In [ ]:
from tradingBot.excel import watchListBook as wb
from tradingBot.excel import positionBook as pb

data_dir = r'C:\Users\jimhu\option_trader\data\charts'

acc_file_path = r'C:\Users\jimhu\option_trader\data\excell\jihuang.xlsm'

watchBook = wb.watchListBook(acc_file_path, data_dir)

watch_list = watchBook.get_all_watch_list()

position_file_path = r'C:\Users\jimhu\option_trader\data\excell\positions.xlsm'
positionBook = pb.positionBook(file_path=position_file_path)

positionBook.get_spread_positions(watch_list)
#positionBook.get_iron_condor_positions(watch_list)
#positionBook.get_butterfly_positions(watch_list)
#positionBook.get_one_leg_positions(watch_list)

In [ ]:
#https://polygon.io/dashboard

In [ ]:
ticker = "AAPL"

# List Aggregates (Bars)
bars = client.get_aggs(ticker=ticker, multiplier=1, timespan="day", from_="2023-01-09", to="2023-01-10")
for bar in bars:
    print(bar)

# Get Last Trade
trade = client.get_last_trade(ticker=ticker)
print(trade)

# List Trades
trades = client.list_trades(ticker=ticker, timestamp="2022-01-04")
for trade in trades:
    print(trade)

# Get Last Quote
quote = client.get_last_quote(ticker=ticker)
print(quote)

# List Quotes
quotes = client.list_quotes(ticker=ticker, timestamp="2022-01-04")
for quote in quotes:
    print(quote)

In [ ]:
##############################################
# get option positions for given symbols     #
##############################################

In [ ]:
import logging
logging.disable(logging.DEBUG)

from tradingBot.excel import positionBook as pb

myBook = pb.positionBook()
myBook.get_position_candidate(['TLT', 'SHY'])

In [ ]:
############################
# update option positions  #
#############################

In [ ]:
import logging
logging.disable(logging.DEBUG)

from tradingBot.excel import positionBook as pb
from tradingBot.settings.tradeConfig import entryCrit, riskManager, marketCondition, runtimeConfig

risk_mgr = riskManager()

risk_mgr.stop_loss_percent = 50
risk_mgr.stop_gain_percent = 100
risk_mgr.close_days_before_earning = 1
risk_mgr.close_days_before_expire = 1
risk_mgr.open_min_days_to_earning = 4
risk_mgr.open_min_days_to_expire = 4
risk_mgr.max_option_positions = 10
risk_mgr.max_loss_per_position = 1500

position_file_path = r'C:\Users\jimhu\option_trader\data\excell\positions.xlsm'
positionBook = pb.positionBook(file_path=position_file_path)

positionBook.update_quotes('Iron Condor 2023-04-18', risk_mgr=risk_mgr)

In [ ]:
not False

In [ ]:
###########################################################
# backtest all strategies for all symbols in watchlist    #
###########################################################

In [ ]:
from tradingBot.backtest.option.single_option import bt_single_option
from tradingBot.backtest.option.spread import bt_spread
from tradingBot.backtest.option.butterfly import bt_butterfly
from tradingBot.backtest.option.credit_iron_condor import bt_credit_iron_condor

strategy_list = [bt_single_option('Put',Credit=False), 
                 bt_single_option('Put'), 
                 bt_single_option('Call',Credit=False),
                 bt_single_option('Call'), 
                 bt_butterfly(Type='Call', Credit=False),
                 bt_butterfly(Type='Call', Credit=True),
                 bt_butterfly(Type='Put', Credit=False), 
                 bt_butterfly(Type='Put', Credit=True),
                 bt_butterfly(Type='Iron', Credit=False),
                 bt_butterfly(Type='Iron', Credit=True),
                 bt_credit_iron_condor(), 
                 bt_spread(Type='Call', Credit=True),
                 bt_spread(Type='Call', Credit=False),
                 bt_spread(Type='Put', Credit=True),
                 bt_spread(Type='Put', Credit=False)]  

watch_list = watchBook.get_all_watch_list()
symbol_list = watch_list['Symbol'].to_list()

from tradeBot.excel import backtestBook as bb

backtest_file_path = r'C:\Users\jimhu\option_trader\assets\static\assets\data\backtest.xlsm' 

backtestBook = bb.backtestBook(backtest_file_path)
today = date.today().strftime("%Y-%m-%d")   
backtestBook.backtest('all ' + today, symbol_list, strategy_list)

In [ ]:
strategy_list = [bt_single_option('Put',Credit=False), 
                 bt_single_option('Put'), 
                 bt_single_option('Call',Credit=False),
                 bt_single_option('Call'), 
                 bt_butterfly(Type='Call', Credit=False),
                 bt_butterfly(Type='Call', Credit=True),
                 bt_butterfly(Type='Put', Credit=False), 
                 bt_butterfly(Type='Put', Credit=True),
                 bt_butterfly(Type='Iron', Credit=False),
                 bt_butterfly(Type='Iron', Credit=True),
                 bt_credit_iron_condor(), 
                 bt_spread(Type='Call', Credit=True),
                 bt_spread(Type='Call', Credit=False),
                 bt_spread(Type='Put', Credit=True),
                 bt_spread(Type='Put', Credit=False)]  

#back test monitor list
acc_file_path = r'C:\Users\jimhu\option_trader\assets\static\assets\data\jihuang.xlsm' 

backtest_file_path = r'C:\Users\jimhu\option_trader\assets\static\assets\data\backtest.xlsm' 

acctLists = AccountWatchListBook(acc_file_path)

watch_list = acctLists.get_watch_list('UpUp')

symbol_list = watch_list[Fundamental_Sheet.SYMBOL_t].to_list()     

backtester = BacktestBook(backtest_file_path)

backtester.backtest('UpUp', symbol_list, strategy_list)

In [ ]:
#loggiFng.disable(logging.INFO)
logger.setLevel(logging.INFO)
pb.update_quotes('One', watch_list)

In [ ]:
from tradingBot.optionPosition import single_leg as sl 
from tradingBot.optionPosition import spread as sp
from tradingBot.optionPosition import iron_condor as ic
from tradingBot.optionPosition import butterfly as bf   
from tradingBot.settings.tradeConfig import entryCrit
from tradingBot.consts import strategy as Strategy

symbol='ORCL'

entry_crit = entryCrit()

spread_pos = sp.spread_position(symbol, entry_crit=entry_crit)

df = spread_pos.get_positions([Strategy.CREDIT_PUT_SPREAD, Strategy.DEBIT_PUT_SPREAD, Strategy.CREDIT_CALL_SPREAD, Strategy.DEBIT_PUT_SPREAD], max_days_to_expire=60)

In [ ]:
df

In [ ]:
from tradingBot.optionPosition import single_leg as sl 
from tradingBot.optionPosition import spread as sp
from tradingBot.optionPosition import iron_condor as ic
from tradingBot.optionPosition import butterfly as bf   
from tradingBot.settings.tradeConfig import entryCrit
from tradingBot.consts import strategy as Strategy

entry_crit = entryCrit()

symbol='OKTA'
iron_condor =ic.iron_condor_position(symbol, entry_crit)
df = iron_condor.get_positions([Strategy.CREDIT_IRON_CONDOR, Strategy.DEBIT_IRON_CONDOR])

In [ ]:
from tradingBot.optionPosition import single_leg as sl 
from tradingBot.optionPosition import spread as sp
from tradingBot.optionPosition import iron_condor as ic
from tradingBot.optionPosition import butterfly as bf   
from tradingBot.settings.tradeConfig import entryCrit
from tradingBot.consts import strategy as Strategy

entry_crit = entryCrit()
entry_crit.min_pnl = 0.5
entry_crit.min_chance_of_win = 25 
entry_crit.min_open_interest = 1
entry_crit.min_opt_vol = 1 
entry_crit.min_delta_for_long = 0
entry_crit.max_delta_for_short = 1

symbol='ORCL'

strategys = [Strategy.CREDIT_CALL_BUTTERFLY, Strategy.CREDIT_PUT_BUTTERFLY, Strategy.DEBIT_CALL_BUTTERFLY, Strategy.DEBIT_PUT_BUTTERFLY, Strategy.IRON_BUTTERFLY, Strategy.REVERSE_IRON_BUTTERFLY]
q =bf.butterfly_position(symbol, entry_crit)
q.get_positions(strategys)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
# Split-out validation dataset
array = df1.values
X = array[:,0:4]
y = array[:,4]
X_train, X_validation, Y_train, Y_validation = train_test_split(X, y, test_size=0.20, random_state=1)

...
# Spot Check Algorithms
models = []
models.append(('LR', LogisticRegression(solver='liblinear', multi_class='ovr')))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC(gamma='auto')))
# evaluate each model in turn
results = []
names = []
for name, model in models:
	kfold = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
	cv_results = cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
	results.append(cv_results)
	names.append(name)
	print('%s: %f (%f)' % (name, cv_results.mean(), cv_results.std()))

In [ ]:
import sys

sys.path.append(r'C:\TWS API\source\pythonclient')
                
from ibapi import wrapper
from ibapi.client import EClient
from ibapi.utils import longMaxString
from ibapi.utils import iswrapper

In [ ]:
import yfinance as yf

In [ ]:
symbol = 'SPY'
q = yf.Ticker(symbol).get_info()

In [8]:
from tradingBot.consts.logConfig import LOGGING

In [5]:
import sys
sys.path.append(r'\Users\jimhu\option_trader\src')

from tradingBot.settings import app_settings  as settings    
    
from pathlib import Path
import os

p = Path(settings.USER_ROOT_DIR+'\\jihuang')

# All subdirectories in the current directory, not recursive.
accounts = [os.path.basename(f) for f in p.iterdir() if f.is_dir() == False]
account_file_list = [f for f in accounts if ('watchlist' in f) == False]

print(account_name_list)
#for f in p.iterdir():
#    if f.is_dir():
#        print(os.path.basename(f))

['jihuang_condor.xlsm', 'jihuang_spread.xlsm']

In [ ]:
user_home_dir = settings.USER_ROOT_DIR+'\\'+self.user_name

In [72]:
from tradingBot.settings import app_settings  as settings    

user_name = 'jihuang'
user_home_dir = settings.USER_ROOT_DIR+'\\'+user_name

import re

string0 = 'jihuang_spread.xlsm'


p = Path(user_home_dir)

pattern = r'(.*)_(.*).x'

account_list = [re.search(r'(.*)_(.*).x', os.path.basename(f)).group(2) for f in p.iterdir() if 'watchlist' not in str(f) and f.is_dir() == False] 

print(account_list)


#match = re.search(pattern, string0)

print(re.search(pattern, string0).group(2))
#print(match.group(0))
#print(match.group(1))
#print(match.group(2))

['condor', 'spread']
spread

In [70]:
import pandas as pd
import yfinance as yf

tickers = ['msft', 'aapl', 'intc', 'tsm', 'goog', 'amzn', 'fb', 'nvda']

tickers = 'msft' # aapl' #, 'intc', 'tsm', 'goog', 'amzn', 'fb', 'nvda']

q = yf.Ticker(tickers) 

df = q.history(period='6mo', interval="1d")

df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-02-15 00:00:00-05:00,267.734725,270.139472,265.599379,268.732544,28922400,0.68,0.0
2023-02-16 00:00:00-05:00,263.444072,266.158140,261.328701,261.578156,29603600,0.00,0.0
2023-02-17 00:00:00-05:00,258.824217,259.522672,255.441597,257.497101,30000100,0.00,0.0
2023-02-21 00:00:00-05:00,253.924900,254.932707,251.041205,252.118851,28397400,0.00,0.0
2023-02-22 00:00:00-05:00,253.535754,253.785209,249.793934,250.961380,22491100,0.00,0.0
...,...,...,...,...,...,...,...
2023-08-09 00:00:00-04:00,326.470001,327.109985,321.049988,322.230011,22373300,0.00,0.0
2023-08-10 00:00:00-04:00,326.019989,328.260010,321.179993,322.929993,20113700,0.00,0.0
2023-08-11 00:00:00-04:00,320.260010,322.410004,319.209991,321.010010,24342600,0.00,0.0
2023-08-14 00:00:00-04:00,321.390015,324.059998,320.079987,324.040009,18808100,0.00,0.0
2023-08-15 00:00:00-04:00,323.000000,325.089996,321.100006,323.412506,11199750,0.00,0.0

In [77]:
import pandas as pd
import pandas_datareader as web
import datetime as dt
watchlist = ['MSFT', 'AAPL', 'AMZN', 'NVDA', 'BLDR', 'GOOGL', 'NFLX', 'META', 'SPY', 'QQQ', 'AMD', 'TSLA', 'ISRG']
start = dt.datetime(2018, 1, 1)
end = dt.datetime(2020, 1, 1)
d = web.DataReader(watchlist, 'stooq', start, end)

Symbols,MSFT,AAPL,AMZN,NVDA,BLDR,GOOGL,NFLX,META,SPY,QQQ,AMD,TSLA,ISRG
Date,,,,,,,,,,,,,
2019-12-31,153.3030,71.9176,92.3920,58.6232,25.41,66.9695,323.57,205.25,308.202,209.021,45.86,27.8887,197.05
2019-12-30,153.1930,71.3983,92.3445,57.8778,25.43,66.9855,323.31,204.41,307.458,208.622,45.52,27.6467,197.11
2019-12-27,154.5430,70.9755,93.4900,59.0139,25.45,67.7320,329.09,208.10,309.163,210.018,46.18,28.6920,199.29
2019-12-26,154.2660,71.0034,93.4385,59.5925,25.39,68.1235,332.63,207.79,309.242,210.197,46.63,28.7293,199.35
2019-12-24,152.9850,69.6226,89.4605,59.4515,25.43,67.2215,333.20,205.12,307.606,208.334,46.54,28.3500,199.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-01-08,83.1341,41.4575,62.3435,54.9370,22.66,55.7105,212.23,188.28,252.632,157.124,12.28,22.4273,130.62
2018-01-05,83.0498,41.6001,61.4570,53.3123,22.78,55.5145,209.99,186.85,252.185,156.547,11.88,21.1053,126.34
2018-01-04,82.0332,41.1366,60.4820,52.8616,22.35,54.8000,205.63,184.33,250.499,155.022,12.12,20.9747,125.64
2018-01-03,81.3164,40.9431,60.2100,52.5818,22.41,54.5760,205.05,184.67,249.429,154.743,11.55,21.1500,127.94
2018-01-02,80.9402,40.9501,59.4500,49.3333,22.00,53.6720,201.07,181.42,247.872,153.249,10.98,21.3687,125.08

In [81]:
d['Close']['MSFT']

Date
2019-12-31    153.3030
2019-12-30    153.1930
2019-12-27    154.5430
2019-12-26    154.2660
2019-12-24    152.9850
                ...
2018-01-08     83.1341
2018-01-05     83.0498
2018-01-04     82.0332
2018-01-03     81.3164
2018-01-02     80.9402
Name: MSFT, Length: 503, dtype: float64

In [83]:
d['Close Diff'] = d['Close'].apply['MSFT'].diff()

In [84]:
d

Attributes     Close
Symbols         MSFT     AAPL     AMZN     NVDA   BLDR    GOOGL    NFLX
Date
2019-12-31  153.3030  71.9176  92.3920  58.6232  25.41  66.9695  323.57  \
2019-12-30  153.1930  71.3983  92.3445  57.8778  25.43  66.9855  323.31
2019-12-27  154.5430  70.9755  93.4900  59.0139  25.45  67.7320  329.09
2019-12-26  154.2660  71.0034  93.4385  59.5925  25.39  68.1235  332.63
2019-12-24  152.9850  69.6226  89.4605  59.4515  25.43  67.2215  333.20
...              ...      ...      ...      ...    ...      ...     ...
2018-01-08   83.1341  41.4575  62.3435  54.9370  22.66  55.7105  212.23
2018-01-05   83.0498  41.6001  61.4570  53.3123  22.78  55.5145  209.99
2018-01-04   82.0332  41.1366  60.4820  52.8616  22.35  54.8000  205.63
2018-01-03   81.3164  40.9431  60.2100  52.5818  22.41  54.5760  205.05
2018-01-02   80.9402  40.9501  59.4500  49.3333  22.00  53.6720  201.07

Attributes                            ...     Volume
Symbols       META      SPY      QQQ  ...       BLDR       GOOGL        NFLX
Date                                  ...
2019-12-31  205.25  308.202  209.021  ...   735922.0  19521220.0   3714837.0  \
2019-12-30  204.41  307.458  208.622  ...   603356.0  20011840.0   4315267.0
2019-12-27  208.10  309.163  210.018  ...   666989.0  23217460.0   5037156.0
2019-12-26  207.79  309.242  210.197  ...   818198.0  23676000.0   3595854.0
2019-12-24  205.12  307.606  208.334  ...   325153.0  13468200.0   2019322.0
...            ...      ...      ...  ...        ...         ...         ...
2018-01-08  188.28  252.632  157.124  ...  1251193.0  24626920.0   5551289.0
2018-01-05  186.85  252.185  156.547  ...  1486193.0  30238600.0   7011226.0
2018-01-04  184.33  250.499  155.022  ...  1508418.0  26049960.0   6022038.0
2018-01-03  184.67  249.429  154.743  ...  2011716.0  31305800.0   8587751.0
2018-01-02  181.42  247.872  153.249  ...  2403074.0  31753540.0  10952410.0

Attributes
Symbols           META           SPY           QQQ          AMD         TSLA
Date
2019-12-31   8962756.0  5.963705e+07  1.851358e+07   31791204.0  154386840.0  \
2019-12-30  10534441.0  5.198829e+07  2.220410e+07   41235735.0  189018975.0
2019-12-27  10287634.0  4.444015e+07  1.845322e+07   36624234.0  149352405.0
2019-12-26   9368273.0  3.239867e+07  1.745344e+07   57712693.0  159724335.0
2019-12-24   6046273.0  2.116804e+07  7.210534e+06   44432192.0  120820800.0
...                ...           ...           ...          ...          ...
2018-01-08  17977498.0  6.198686e+07  2.391939e+07   63163299.0  147555480.0
2018-01-05  13557556.0  8.969992e+07  2.789595e+07   63654090.0   68838660.0
2018-01-04  13864983.0  8.724864e+07  2.558268e+07  109314694.0  149194260.0
2018-01-03  16880049.0  9.688064e+07  3.033433e+07  153336333.0   66893295.0
2018-01-02  18130091.0  9.369272e+07  3.363622e+07   43885015.0   65188275.0

Attributes            Close Diff
Symbols          ISRG
Date
2019-12-31  1344156.0        NaN
2019-12-30  1133070.0    -0.1100
2019-12-27  1287162.0     1.3500
2019-12-26   996429.0    -0.2770
2019-12-24   838878.0    -1.2810
...               ...        ...
2018-01-08  2901906.0     0.0555
2018-01-05  2099184.0    -0.0843
2018-01-04  2696394.0    -1.0166
2018-01-03  2365410.0    -0.7168
2018-01-02  2483691.0    -0.3762

[503 rows x 66 columns]